# Generated by Django 3.1.2 on 2020-12-22 15:55

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_auto_20201222_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
