# Generated by Django 3.1.2 on 2020-12-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0002_auto_20201223_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
