# Generated by Django 3.1.2 on 2020-12-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0003_auto_20201223_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=12, upload_to='images'),
            preserve_default=False,
        ),
    ]
